when:
  - branch: main
  - event: tag

steps:
  - name: goreleaser
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --clean
    environment:
      GOPRIVATE: github.com/SencilloDev
      GITHUB_TOKEN:
        from_secret: github_token
