steps:
  - name: send telegram notification
    when:
      event: push
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: telegram_token
      to: 
        from_secret: telegram_group

