name: test
on: 
  push:
    paths:
      - '**.go'
  workflow_call:
jobs:
  test:
    strategy:
      matrix:
    runs-on: "self-hosted"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Coverage
        run: make coverage
      - name: store coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: ./coverage.html 
